# package: entry
# SCCS: @(#)entry.yaml	1.2 12/24/18 

shell_command:
  set_front_door_closed: '/home/homeassistant/.homeassistant/bin/isysetvar.py Front_Door Off'
  set_front_door_opened: '/home/homeassistant/.homeassistant/bin/isysetvar.py Front_Door On'

automation:
  - alias: Front Door Closed
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        from: 'on'
        to: 'off'
    action:
      service: shell_command.set_front_door_closed

  - alias: Front Door Open
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door  
        from: 'off'
        to: 'on'
    action:
      service: shell_command.set_front_door_opened
