# package: garage
# SCCS: @(#)garage.yaml	1.4 01/30/19 

homeassistant:
  customize:

# Garage
    switch.garage_door_left_sensor:
      friendly_name: Left Garage Door
      device_class: garage_door
      icon: mdi:garage
    switch.garage_door_right_sensor:
      friendly_name: Right Garge Door
      device_class: garage_door
      icon: mdi:garage

shell_command:
  set_garage_door_closed: '/home/homeassistant/.homeassistant/bin/isysetvar.py Garage_Entry Off'
  set_garage_door_opened: '/home/homeassistant/.homeassistant/bin/isysetvar.py Garage_Entry On'

cover:
  - platform: template
    covers:
      left_garage_door:
        friendly_name: Left Garage Door
        value_template: "{{ is_state('switch.garage_door_left_sensor', 'off') }}"
        close_cover:
          service: script.close_left_garage_door
        open_cover:
          service: script.open_left_garage_door
        icon_template: >-
          {% if is_state('switch.garage_door_left_sensor', 'on') %}
            mdi:garage
          {% else %}
            mdi:garage-open
          {% endif %}
  - platform: template
    covers:
      right_garage_door:
        friendly_name: Right Garage Door
        value_template: "{{ is_state('switch.garage_door_right_sensor', 'off') }}"
        close_cover:
          service: script.close_right_garage_door
        open_cover:
          service: script.open_right_garage_door
        icon_template: >-
          {% if is_state('switch.garage_door_right_sensor', 'on') %}
            mdi:garage
          {% else %}
            mdi:garage-open
          {% endif %}

automation:
  - alias: Garage Entry Door Opened
    trigger:
      - platform: state
        entity_id: binary_sensor.garage_entry_door
        from: 'off'
        to: 'on'
    action:
      service: shell_command.set_garage_door_opened

  - alias: Garage Entry Door Closed
    trigger:
      - platform: state
        entity_id: binary_sensor.garage_entry_door
        from: 'on'
        to: 'off'
    action:
      service: shell_command.set_garage_door_closed

script:
  open_left_garage_door:
    alias: "Open Left Garage Door"
    sequence:
      - condition: state
        entity_id: switch.garage_door_left_sensor
        state: 'on'
      - service: switch.turn_on
        entity_id: switch.garage_door_left_relay
      - delay:
          seconds: 5
      - service: switch.turn_off
        entity_id: switch.garage_door_left_relay

  close_left_garage_door:
    alias: "Close Left Garage Door"
    sequence:
      - condition: state
        entity_id: switch.garage_door_left_sensor
        state: 'off'
      - service: switch.turn_on
        entity_id: switch.garage_door_left_relay
      - delay:
          seconds: 5
      - service: switch.turn_off
        entity_id: switch.garage_door_left_relay

  open_right_garage_door:
    alias: "Open Right Garage Door"
    sequence:
      - condition: state
        entity_id: switch.garage_door_right_sensor
        state: 'on'
      - service: switch.turn_on
        entity_id: switch.garage_door_right_relay
      - delay:
          seconds: 5
      - service: switch.turn_off
        entity_id: switch.garage_door_right_relay

  close_right_garage_door:
    alias: "Close Right Garage Door"
    sequence:
      - condition: state
        entity_id: switch.garage_door_right_sensor
        state: 'off'
      - service: switch.turn_on
        entity_id: switch.garage_door_right_relay
      - delay:
          seconds: 5
      - service: switch.turn_off
        entity_id: switch.garage_door_right_relay


