# package: health.yaml
# SCCS: @(#)health.yaml	1.1 02/23/19 

sensor:
  platform: pollen
  zip_code: "92024"
  monitored_conditions:
    - allergy_average_forecasted
    - allergy_average_historical
    - allergy_index_today
    - allergy_index_tomorrow
    - allergy_index_yesterday
    - asthma_average_forecasted
    - asthma_average_historical
    - asthma_index_today
    - asthma_index_tomorrow
    - asthma_index_yesterday
    - disease_average_forecasted
